import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import { Inter } from "next/font/google";

import AntdProvider from "shared/providers/ant/AntdProvider";
import '../public/antd.min.css';
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdProvider>{children}</AntdProvider>
      </body>
    </html>
  );
}

